StelmakApp/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'StelmakApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('programm_model_form/', views.programm_model_form, name='programm_model_form'),
    path('programm_result/', views.programm_result, name='programm_result'),
    path('table/', views.table, name='table'),
    path('datetimenow/', views.datetimenow, name='datetimenow'),
    path('admin/', admin.site.urls),
    path('programm_form/', views.programm_form, name='programm_form')
]

StelmakApp_2/urls.py
from django.urls import path
from . import views

app_name = 'StelmakApp_2'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_me/', views.about_me, name='about_me'),
    path('about_uni/', views.about_uni, name='about_uni'),
    path('about_management', views.about_managment, name='about_managment'),
    path('about_friends', views.about_friends, name='about_friends'),
    path('about_programm_read', views.about_programm_read, name='about_programm_read')
]

project02/urls.py
from django.contrib import admin
from django.urls import path, include
from StelmakApp_2 import views as app2_views  # импортируем views второго приложения

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', app2_views.index, name='index'),  # главная страница
    path('app1/', include('StelmakApp.urls')),
    path('app2/', include('StelmakApp_2.urls')),
]

StelmakApp/models.py
from django.db import models

# import datetime

courses_choices = (
    (1, 'первый'),
    (2, "второй"),
    (3, "третий"),
    (4, "четвёртый"),
)


class Educational_ProgrammModel(models.Model): #столбцы в таблице
    name = models.CharField(
        verbose_name="ФИО",
        default='Смирнов Иван Иванов',
        max_length=500,
    )
    date_of_birth = models.DateField(
        verbose_name="Дата рождения", #здесь можно изменить формат на дату,
        default='2004-05-10',

    )
    year = models.IntegerField(
        verbose_name="Год поступления", default=2022
    )
    courses = models.IntegerField(
        verbose_name="Курс",
        choices=courses_choices,
        default=3,
        help_text='от 1 до 4'
    )
    last_year = models.IntegerField(
        verbose_name="Год выпуска",
        default=2026,
        max_length=255,
    )
    result = models.IntegerField(
        verbose_name="Сколько осталось учиться",
        default=4,
        max_length=255,
    )
    current_date = models.DateTimeField(
        verbose_name="Дата изменения(save)", auto_now=True
    )

    def __str__(self):
        # return self.task
        # return '%s %s' % (self.task, self.current_date)
        return f"self.id:{self.id}; self.task:{self.name}"

    class Meta:
        verbose_name = "Я_и_программа_Таблица"
        verbose_name_plural = "Я_и_программа_Таблицы"
        ordering = ("-pk", )


# current_date = models.DateTimeField("ДатаВремя", default=datetime.datetime.now())
# current_date = models.DateTimeField("ДатаВремя", auto_now_add=True)

# python manage.py makemigrations
# python manage.py migrate

# admin.py
# from django.contrib import admin
# # Register your models here.
# from .models import Abc
# admin.site.register(Abc)


# forms.py
# from django.forms import ModelForm
# from .models import Abc
#
# class CreateAbcForm(ModelForm):
#     class Meta:
#         model = Abc
#         fields = ['task', 'a' ,'b' ,'c', 'c_calc']

StelmakApp/forms.py
# from django.forms import ModelForm
from django import forms
from django.forms import ModelForm
from .models import Educational_ProgrammModel


class ProgrammForm(forms.Form):
    name = forms.CharField(initial = "Иван Иванович Иванов")
    date_of_birth = forms.IntegerField(initial=2005, min_value=1950) #здесь можно изменить формат на дату
    year = forms.IntegerField(initial=2023,required=False)
    courses = forms.IntegerField(initial=1)
    last_year = forms.IntegerField(initial=2027)



class Educational_ProgrammModelFrom(ModelForm):
    # task = forms.CharField(widget=forms.Textarea({'cols': '60', 'rows': "3"}))
    # task.widget.attrs.update({'cols': '40', 'rows': "2"})
    class Meta:
        model = Educational_ProgrammModel
        fields = '__all__'
        # fields = ['task', 'a', 'b','c']
        print('\nfields: ', fields)

StelmakApp/views.py
from django.shortcuts import render
import datetime, math
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db.models import Count, Avg, Min, Max, StdDev, Sum
from .models import Educational_ProgrammModel
from .forms import Educational_ProgrammModelFrom, ProgrammForm

def index(request):
    return render(request, "StelmakApp/index.html")

def programm_model_form(request):
    print("request.method: ", request.method)
    if request.method == "POST":
        form = Educational_ProgrammModelFrom(request.POST)
        if form.is_valid():
            print(form.errors)
            print("\nform_is_valid:\n", form)
            form.save()
            return redirect("StelmakApp:programm_result")
        if not form.is_valid():
            print(form.errors)
    else:
        form = Educational_ProgrammModelFrom()
        print("\nform_else:\n", form)
    context = {"form": form}
    print("\ncontext:\n", context)
    return render(request, "StelmakApp/programm_model_form.html", context)

def solution(courses):
    result = 4-courses
    return result


def programm_result(request):
    object_list = Educational_ProgrammModel.objects.all().order_by("id")
    print("\n\nobject_list: ", object_list)

    last_object = object_list.values("name", "date_of_birth", "year", "courses", "last_year", "result")[0]
    print("\n\nlast_object: ", last_object)
    name_formulation = object_list.values("name")[0]
    name_id = object_list.values("id")[0]["id"]
    print("task_id task_formulation: ", name_id, name_formulation)


    result = solution(last_object['courses'])
    print("\nresult: ", result)
  
    
    
    update_obj = Educational_ProgrammModel.objects.filter(id=name_id)
    update_result = result
    update_obj.update(result = update_result )

    # list
    values_list = object_list.values_list()[0]
    print("\nvalues_list: ", values_list)
    name_formulation = values_list[1]
    print("\ntask_formulation: ", name_formulation)
    last_values = [values_list[1], values_list[2], values_list[3], values_list[4], values_list[5], values_list[6]]
    print("\nlast_values:", last_values)


    context = {
        "last_object": last_object,
        "name_formulation": name_formulation,
        "last_values": last_values,
        "result": result,
    }
    return render(request, "StelmakApp/programm_result.html", context)

def table(request):
    objects_values = Educational_ProgrammModel.objects.values()
    print("\nobjects_values:", objects_values)
    objects_values_list = (
        Educational_ProgrammModel.objects.values_list().filter(courses=3).order_by("name")
    ) 
    print("\nobjects_values_list:", objects_values_list)
    cur_objects = objects_values_list
    statics_val = [
        cur_objects.aggregate(Avg("courses")),
        cur_objects.aggregate(Min("courses")),
        cur_objects.aggregate(Max("courses")),
        cur_objects.aggregate(Sum("result")),
    ]
    print("\nstatics_val:", statics_val)
    statics = {"statics_val": statics_val}
    # fields_name
    fields = Educational_ProgrammModel._meta.get_fields()
    print("\nfields", fields)
    verbose_name_list = []
    name_list = []
    for e in fields:
        verbose_name_list.append(e.verbose_name)
        name_list.append(e.name)
    print("\nverbose_name_list:", verbose_name_list)
    print("\nname_list", name_list)
    field_names = verbose_name_list
    context = {
        "objects_values": objects_values,
        "name_list": name_list,
        "objects_values_list": objects_values_list,
        "verbose_name_list": verbose_name_list,
        "statics": statics,
        "field_names": field_names,
    }
    return render(request, "StelmakApp/table.html", context)

def datetimenow (request):
    datetime_now: datetime = datetime.datetime.now()
    context = {'key': datetime_now}
    return render (request, 'StelmakApp/datetime_now.html', context)

def programm_form(request):
    programm_form = ProgrammForm()
    return render(request, "programm_form.html", {"programm_form": programm_form})

def programm_get(request):
    print(request.GET)
    name_value = (request.GET.get("name"))
    date_of_birth_value = int(request.GET.get("date_of_birt"))
    year_value =int(request.GET.get("year")) 
    courses_value = int(request.GET.get("courses")) 
    last_year_value = int(request.GET.get('last_year'))
    new_object = Educational_ProgrammModel(name=name_value, date_of_birth=date_of_birth_value, year=year_value, courses = courses_value, last_year=last_year_value)
    new_object.save()
    return redirect("StelmakApp:programm_result")

StelmakApp/templates/StelmakApp/about.html
{% extends 'StelmakApp/base.html' %}

{% block title %}
О нас
{% endblock %}

{% block small %}
О нас<br />
{% endblock %}

{% block content %}
  {% load static %}
  <h5 class="card-title text-center">Информация о программе</h5> 

  <div class="card">
    <div class="card-body">
      <ul class="d-flex flex-row flex-wrap">
        <h5 class="card-title text-center">Обо мне</h5>
        {% for object in dict_of_array.me %}
        <li class="m-2 list-group-item bg-light border p-3">
          <img src="{% static object.img %}" class="student-img" />
          <b>ФИО:</b><p>{{ object.name }}</p>
          <b>Электронная почта:</b><p>{{ object.email }}</p>
          <b>Телефон:</b><p>{{ object.phone }}</p>
        </li>
      </ul>
      {% endfor %}
      <h5 class="card-title text-center">Филология</h5>
      <p><b>Описание программы:</b>Это область знания, состоящая из совокупности наук, изучающих духовную культуру человечества, выраженную словом, и ее историческое развитие.</p>

        Чтобы изучить русскую филологию, требуется знание европейских языков и западной гуманитарной традиции. Система образования НИУ ВШЭ впервые начала параллельное обучение филологии России и Европы.</p>
      <ul class="d-flex flex-row flex-wrap">
        {% for object in dict_of_array.info %}
          <li class="m-2 list-group-item bg-light border p-3">
            <img src="{% static object.img %}" class="student-img" />
            <h5>{{ object.job }}</h5>
            <h6>{{ object.name }}</h6>
            <p>
              {{ object.email }}
            </p>
          </li>
        {% endfor %}
      </ul>
    </div>

    <h5 class="card-title text-center">Сокурсники</h5>
    <div class="card-body">
      <table class="table, border">
        <tbody>
          <tr class="border">
            <td>ФИО</td>
            <td>Фотография</td>
            <td>Электронная почта</td>
          </tr>
          {% for object in dict_of_array.info_classmates %}
            <tr class="border">
              <td>{{ object.name }}</td>
              <td>
                <img src="{% static object.img %}" class="student-img" />
              </td>
              <td>{{ object.email }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

StelmakApp/templates/StelmakApp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
   body {
    background: linear-gradient(to right, #1e3c72, #2a5298);
    color: white;
}

</style>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">

    <!-- Custom Styles -->
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Poppins', sans-serif;
        }
        .bg-color {
            background: linear-gradient(90deg, #0d6efd, #495057);
            color: white;
        }
        h1.card-title {
            margin: 0;
            font-weight: 600;
            font-size: 1.8rem;
            text-align: center;
        }
        header.card,
        nav.card,
        main.card {
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);
            border-radius: 8px;
        }
        nav.card {
            border-left: 5px solid #0d6efd;
        }
        main.card {
            border-left: 5px solid #198754;
        }
        h3 {
            border-bottom: 2px solid #dee2e6;
            padding-bottom: 0.5rem;
            margin-bottom: 1rem;
            font-weight: 500;
            color: #343a40;
        }
    </style>
</head>

<body>
    <div class="container my-4">
        <header class="card mb-3">
            <div class="card-body bg-color">
                <h1 class="card-title">Я и моя образовательная программа</h1>
            </div>
        </header>

        <nav class="card mb-3">
            <div class="card-header bg-light">
                {% include 'StelmakApp/navigation.html' %}
            </div>
        </nav>

        <main class="card mb-3">
            <div class="card-body bg-white">
                <h3>{% block small %}{% endblock %}</h3>
                {% block content %}{% endblock %}
            </div>
        </main>
    </div>
</body>

</html>

StelmakApp/templates/StelmakApp/datetime_now.html
{% extends 'StelmakApp/base.html' %}

{% block title %}
Time now
{% endblock %}

{% block small %}
Настоящее время
{% endblock %}

{% block content %}
    datetime_now: {{ key }}
{% endblock %}

StelmakApp/templates/StelmakApp/index.html
{% extends 'StelmakApp/base.html' %}
{% block title %}
Главная страница
{% endblock %}

{% block small %}
Главная страница
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% endblock %}

StelmakApp/templates/StelmakApp/navigation.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

<nav>
  <ul class="nav nav-tabs card-header-tabs">

    <li class="nav-item">
      <a class="nav-link" href="{% url 'StelmakApp:index' %}">Главная</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}">Панель администратора</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'StelmakApp:programm_model_form' %}">Форма</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'StelmakApp:programm_result' %}">Последнее вхождение</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'StelmakApp:table' %}">Таблица</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'StelmakApp:datetimenow' %}">Время</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'StelmakApp_2:about_me' %}">Приложение 2</a>
    </li>
  </ul>
</nav>

StelmakApp/templates/StelmakApp/programm_model_form.html
{% extends 'StelmakApp/base.html' %}

{% block title %}
Форма
{% endblock %}

{% block small %}
Форма
{% endblock %}

{% block content %}
<form action= "{% url 'StelmakApp:programm_model_form' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <label for="id_submit">&nbsp;</label>
    <button type="submit" id="id_submit">Добавить</button>
    </label>
</form>
{% endblock %}

StelmakApp/templates/StelmakApp/programm_result.html
{% extends 'StelmakApp/base.html' %}

{% block title %}
Последнее вхождение
{% endblock %}

{% block small %}
Последнее вхождение
{% endblock %}

{% block content %}
    <h6>{{ task_formulation }}</h6>
    <style>
        table th, table td {
            text-align: center;
            vertical-align: middle;
            min-width: 175px;
            word-wrap: break-word;
        }
        table {
            table-layout: fixed;
            width: 100%;
        }
    </style>

    <table class="table table-bordered">
        <thead class="table-light">
            <tr>
                <th>ФИО</th>
                <th>Дата рождения</th>
                <th>Год поступления</th>
                <th>Курс</th>
                <th>Год выпуска</th>
                <th>Результат</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for item in last_values %}
                    <td>{{ item }}</td>
                {% endfor %}
            </tr>
        </tbody>
    </table>
{% endblock %}

StelmakApp/templates/StelmakApp/table.html
{% extends 'StelmakApp/base.html' %}

{% block title %}
Таблица
{% endblock %}

{% block small %}
Таблица
{% endblock %}

{% block content %}
    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
        <tr>
            {% for name in name_list %}
                <td>{{ name }}</td>
            {% endfor %}
        </tr>
        {% for object in objects_values %}
            <tr>
                {% for key, value in object.items %}
                    <td>
                        {{ value }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h6>Таблица после фильтрации и сортировки</h6>
    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
        <tr>
            {% for name in verbose_name_list %}
                <td>{{ name }}</td>
            {% endfor %}
        </tr>
        {% for objects_values in objects_values_list %}
            <tr>
                {% for item in objects_values %}
                    <td>
                        {{ item }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <p>Статистика после фильтрации и сортировки </p>
    {#    {% autoescape off %}{{ statics.statics_val }}{% endautoescape %}#}
    {% for item in statics.statics_val %}
        {% for k, v in  item.items %}
            {{ k }}:  {{ v }};
            {#            {% autoescape off %}{{ k }}:  {{ v }}; {% endautoescape %}#}
        {% endfor %}
    {% endfor %}
{% endblock %}